# Generated by Django 5.2.15 on 2026-06-13 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0003_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
